# Generated by Django 5.0.6 on 2024-07-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(default='Rental', max_length=40),
            preserve_default=False,
        ),
    ]
