# Generated by Django 5.0.6 on 2024-07-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('lease', 'Lease'), ('rental', 'Rental'), ('buying', 'Buying')], max_length=40),
        ),
    ]
