# Generated by Django 5.0.6 on 2024-07-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_is_approved_listing_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
